version: "3.8"

services:
  web:
    build: .
    restart: always
    container_name: "libreddit"
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s